spring:
  application:
    name: ${APP_NAME}
# Database Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
#    JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


#  Server Configuration
server:
  port: ${APP_PORT}
  servlet:
    context-path: ${APP_URL}


